# Generated by Django 5.2.6 on 2026-01-28 22:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('item', 'Item'), ('service', 'Service')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
                ('residence', models.CharField(choices=[('carrefour_sherbrooke', 'Carrefour Sherbrooke'), ('new_residence', 'New Residence'), ('la_citadelle', 'La Citadelle'), ('royal_victoria', 'Royal Victoria College'), ('molson', 'Molson'), ('mcconnell', 'McConnell'), ('university_hall', 'University Hall'), ('douglas_hall', 'Douglas Hall'), ('solin_hall', 'Solin Hall'), ('laird_hall', 'Laird Hall'), ('off_campus', 'Off Campus')], max_length=50)),
                ('is_sold', models.BooleanField(default=False)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
