# Generated by Django 5.2.6 on 2026-01-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='is_sold',
        ),
    ]
