# Generated by Django 5.2.6 on 2026-01-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listings_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
