# Generated by Django 5.2.6 on 2026-01-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listings_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
