# Generated by Django 5.2.6 on 2026-01-29 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence', models.CharField(blank=True, choices=[('carrefour_sherbrooke', 'Carrefour Sherbrooke'), ('new_residence', 'New Residence'), ('la_citadelle', 'La Citadelle'), ('royal_victoria', 'Royal Victoria College'), ('molson', 'Molson'), ('mcconnell', 'McConnell'), ('university_hall', 'University Hall'), ('douglas_hall', 'Douglas Hall'), ('solin_hall', 'Solin Hall'), ('laird_hall', 'Laird Hall'), ('off_campus', 'Off Campus')], max_length=255, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile_avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
