# Generated by Django 5.2.6 on 2026-01-29 21:51
import os
from django.db import migrations

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    ADMIN_USER = os.environ.get('ADMIN_USER')
    ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL')
    ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD')

    if not all([ADMIN_USER, ADMIN_EMAIL, ADMIN_PASSWORD]):
        # If environment variables are not set, do nothing.
        # This prevents errors and allows the migration to run without creating a user.
        print("Superuser creation skipped: Environment variables not set.")
        return

    if not User.objects.filter(username=ADMIN_USER).exists():
        print(f"Creating superuser: {ADMIN_USER}")
        User.objects.create_superuser(
            username=ADMIN_USER,
            email=ADMIN_EMAIL,
            password=ADMIN_PASSWORD
        )
    else:
        print(f"Superuser {ADMIN_USER} already exists.")


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
